import {readFile,writeFile} from 'node:fs/promises';
const dir=new URL('./',import.meta.url);
const {shots,capturedAt}=JSON.parse(await readFile(new URL('manifest.json',dir),'utf8'));
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const recommended=[1,3,6,7,8,9,11,12,13,15,18,19,20,17];
const note='ภาพหน้าจอจากแอป TokTickIT จริง โดยใช้ฐานข้อมูล demo แยกจากฐานข้อมูลใช้งาน ชื่อและข้อมูลคำร้องเป็นข้อมูลตัวอย่าง ภาพชุดนี้เป็นหลักฐาน demo UI ไม่ใช่หลักฐานยืนยันการทดสอบครบทุก requirement';
await writeFile(new URL('README.md',dir),`# TokTickIT — Lab 3 Demo Screenshots\n\n${note}\n\nแคปเมื่อ: ${capturedAt}\n\nเปิด index.html เพื่อดูภาพรวม กดภาพเพื่อเปิด PNG ต้นฉบับ\n\n## ภาพที่แนะนำสำหรับรายงาน\n\n${recommended.map(n=>String(n).padStart(2,'0')).join(', ')}\n\nถ้าพื้นที่จำกัด ใช้ภาพ 11 และ 12 แยกแทนภาพเต็ม 10 และใช้ภาพ 17 แทนภาพยาว 16\n\n## คำบรรยายภาพพร้อมใช้\n\n${shots.map((s,i)=>`### ภาพที่ ${i+1}: ${s.title}\n\n![${s.title}](${s.file})\n\n${s.caption}\n`).join('\n')}\n## วิธีแคปซ้ำ\n\nจากโฟลเดอร์ toktickit รัน:\n\n\`node artifacts/lab-03/demo-report/capture-runner.mjs\`\n\nต้องมี TEST_DATABASE_URL ใน server/.env, dependencies และ Chromium ของ Playwright สคริปต์สร้าง schema ทดสอบชั่วคราวและล้างเมื่อเสร็จ ใช้พอร์ต 3101 และ 4175 แล้วรัน \`node artifacts/lab-03/demo-report/build-gallery.mjs\` เพื่ออัปเดตหน้ารวมภาพ\n`,'utf8');
await writeFile(new URL('index.html',dir),`<!doctype html><html lang="th"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TokTickIT Lab 3 — Demo screenshots</title><style>*{box-sizing:border-box}body{margin:0;background:#f2f6f5;color:#17382c;font:16px/1.7 'Leelawadee UI',Tahoma,sans-serif}header{padding:40px max(24px,calc((100vw - 1200px)/2));background:#073e30;color:white}header p{max-width:1000px}h1{margin:0}main{max-width:1248px;margin:auto;padding:24px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(330px,1fr));gap:24px}article{padding:20px;background:white;border-radius:14px;border:1px solid #d6e4df;break-inside:avoid}h2{font-size:19px;margin:0 0 12px}img{display:block;width:100%;height:270px;object-fit:contain;object-position:top;background:#f5f8f7;border:1px solid #e0e8e4}a{color:#007b55}small{color:#587065}article p{margin:12px 0}.tag{font-size:12px;background:#e0f3e9;color:#006545;padding:3px 8px;border-radius:6px}@media print{header{padding:20px;color:#17382c;background:white}.grid{grid-template-columns:1fr 1fr}article{border-radius:0}img{height:210px}}</style><header><h1>TokTickIT · Lab 3</h1><p>ชุดภาพสำหรับรายงาน Demo App · ${shots.length} ภาพ พร้อมคำบรรยายภาษาไทย</p><p>${note}</p></header><main><p>กดภาพเพื่อเปิด PNG ขนาดจริง · <a href="README.md">คำบรรยายทั้งหมด</a> · ป้าย “แนะนำ” คือภาพหลักที่เหมาะสำหรับเลือกใส่รายงาน</p><div class="grid">${shots.map((s,i)=>`<article><h2>${String(i+1).padStart(2,'0')} · ${esc(s.title)} ${recommended.includes(i+1)?'<span class="tag">แนะนำ</span>':''}</h2><a href="${s.file}"><img src="${s.file}" alt="${esc(s.title)}" loading="lazy"></a><p>${esc(s.caption)}</p><small>${s.file}</small></article>`).join('')}</div></main></html>`,'utf8');
console.log(`Built gallery and Thai captions for ${shots.length} images.`);
