import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { mkdir, writeFile } from 'node:fs/promises';
const require = createRequire(new URL('../../../client/package.json', import.meta.url));
const { chromium, expect } = require('@playwright/test');
const directory = fileURLToPath(new URL('./', import.meta.url));
const browser = await chromium.launch({headless:true});
const context = await browser.newContext({viewport:{width:1440,height:1000}, deviceScaleFactor:1, locale:'en-US', timezoneId:'Asia/Bangkok', baseURL:process.env.E2E_CLIENT_URL});
const page = await context.newPage();
const shots=[];
const password=process.env.E2E_AUTH_PASSWORD;
async function shot(file,title,caption,locator) {
  await page.waitForLoadState('networkidle');
  await page.evaluate(async()=>{await document.fonts.ready;document.activeElement?.blur();});
  if (!locator) await page.evaluate(()=>window.scrollTo(0,0));
  await (locator ?? page).screenshot({path:directory+file, ...(!locator?{fullPage:true}:{}),animations:'disabled'});
  shots.push({file,title,caption,url:page.url(),viewport:page.viewportSize()});
  console.log('Captured '+file);
}
async function login(email,pwd=password){
  await page.goto('/login');
  await page.getByLabel('Email',{exact:false}).fill(email);
  await page.getByLabel('Password',{exact:false}).fill(pwd);
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
}
async function logout(){await page.getByRole('button',{name:'Logout',exact:true}).click();await expect(page.getByRole('heading',{name:'Sign in',exact:true})).toBeVisible();}
try {
  await mkdir(directory,{recursive:true});
  await page.goto('/login');
  await expect(page.getByRole('heading',{name:'Sign in',exact:true})).toBeVisible();
  await shot('01-login.png','เข้าสู่ระบบ','หน้า Sign in สำหรับเข้าสู่ระบบด้วยอีเมลและรหัสผ่าน');
  await login('auth-browser@example.test','Wrong-demo-password1!');
  await expect(page.getByRole('alert')).toContainText('Unable to sign in');
  await shot('02-login-invalid.png','รหัสผ่านไม่ถูกต้อง','ระบบแสดงข้อความปฏิเสธการเข้าสู่ระบบเมื่อใช้รหัสผ่านไม่ถูกต้อง');
  await login('auth-browser@example.test');
  await expect(page.getByRole('heading',{name:'Change your initial password'})).toBeVisible();
  await shot('03-change-initial-password.png','เปลี่ยนรหัสผ่านครั้งแรก','ผู้ใช้ต้องตั้งรหัสผ่านใหม่ก่อนเข้าถึงฟังก์ชันภายในระบบ');
  await page.getByLabel('Current Password',{exact:false}).fill(password);
  await page.getByLabel('New Password',{exact:false}).first().fill('Demo-Changed-password2!');
  await page.getByLabel('Confirm New Password',{exact:false}).fill('Demo-Changed-password2!');
  await page.getByRole('button',{name:'Save password'}).click();
  await expect(page.getByRole('heading',{name:'Create Ticket',exact:true})).toBeVisible();
  await shot('04-requester-create-ticket.png','Requester: สร้างคำร้อง','หลังเปลี่ยนรหัสผ่านสำเร็จ ผู้ใช้เข้าสู่หน้าสร้าง Ticket พร้อมแสดงตัวตนที่เข้าสู่ระบบ');
  await page.getByRole('link',{name:'My Tickets',exact:true}).click();
  await expect(page.getByText('Printer on floor 3 is offline',{exact:true}).first()).toBeVisible();
  await shot('05-requester-my-tickets.png','Requester: รายการคำร้อง','ผู้แจ้งติดตาม Ticket ของตนเองผ่านหน้า My Tickets');
  await logout();
  await login('queue-browser@example.test');
  await expect(page.getByRole('heading',{name:'Ticket Queue',exact:true})).toBeVisible();
  await expect(page.getByRole('status')).toContainText('23 tickets');
  await shot('06-staff-ticket-queue.png','IT Staff: คิวงาน','ตารางคิวงานแสดงสถานะ Requested Priority, IT Priority และผู้รับผิดชอบ พร้อมค้นหาและกรองข้อมูล');
  await page.getByLabel('Search',{exact:true}).fill('printer');
  await page.getByLabel('Owner',{exact:true}).selectOption('me');
  await page.getByRole('button',{name:'Apply filters'}).click();
  await expect(page.getByRole('status')).toContainText('1 tickets');
  await shot('07-staff-search-filter.png','IT Staff: ค้นหาและกรอง','ค้นหาคำว่า printer และกรองงานของตนเอง ได้ผลลัพธ์ตรงเงื่อนไขหนึ่งรายการ');
  await page.getByRole('button',{name:'Clear filters'}).click();
  await page.getByLabel('Search',{exact:true}).fill('TKT-2026-000002');
  await page.getByRole('button',{name:'Apply filters'}).click();
  await expect(page.getByRole('status')).toContainText('1 tickets');
  await page.getByRole('link',{name:/View ticket/}).click();
  await expect(page.getByRole('heading',{name:'Ticket Detail',exact:true})).toBeVisible();
  const id=page.url().split('/').pop();
  await shot('08-staff-ticket-detail.png','IT Staff: รายละเอียดคำร้อง','รายละเอียด Ticket ก่อนรับงาน พร้อมปุ่ม Claim Ticket ตัวเลือกผู้รับผิดชอบ สถานะ ความสำคัญ และไฟล์แนบ');
  await page.getByRole('button',{name:'Claim Ticket',exact:true}).click();
  await expect(page.getByLabel('Ticket Owner',{exact:true}).locator('option:checked')).toHaveText('Mali IT Staff');
  await page.getByLabel('IT Priority',{exact:true}).selectOption('LOW');
  await expect(page.getByLabel('IT Priority',{exact:true})).toHaveValue('LOW');
  await page.getByLabel('Status',{exact:true}).selectOption('OPEN');
  await expect(page.getByLabel('Status',{exact:true})).toHaveValue('OPEN');
  await page.getByLabel('Status',{exact:true}).selectOption('IN_PROGRESS');
  await expect(page.getByLabel('Status',{exact:true})).toHaveValue('IN_PROGRESS');
  await shot('09-staff-claim-priority-status.png','IT Staff: รับงานและอัปเดตสถานะ','หลัง Claim Ticket เจ้าหน้าที่ Mali IT Staff เป็นผู้รับผิดชอบ ปรับ IT Priority เป็น Low และสถานะเป็น In Progress');
  await page.getByLabel('Public Comment',{exact:true}).fill('The network cable has been replaced. Please test the workstation again.');
  await page.getByRole('button',{name:'Post Public Comment'}).click();
  await expect(page.getByText('Public Comment posted.')).toBeVisible();
  await page.getByLabel('Internal Note',{exact:true}).fill('Diagnostic check: faulty Ethernet cable replaced. Connectivity verified by IT.');
  await page.getByRole('button',{name:'Add Internal Note'}).click();
  await expect(page.getByText('Internal Note posted.')).toBeVisible();
  await shot('10-staff-comments-and-notes.png','IT Staff: ความคิดเห็นและบันทึกภายใน','Public Comments ใช้สื่อสารกับผู้แจ้ง ส่วน Internal Notes แสดงเฉพาะ IT Staff และ Administrator');
  await shot('11-public-comment-closeup.png','Public Comment','เจ้าหน้าที่แจ้งผลการแก้ไขผ่านความคิดเห็นที่ผู้แจ้งอ่านได้',page.getByRole('region',{name:'Public Comments',exact:true}));
  await shot('12-internal-note-closeup.png','Internal Note','บันทึกผลวิเคราะห์ภายในสำหรับทีม IT',page.getByRole('region',{name:'Internal Notes',exact:true}));
  await logout();
  await login('auth-browser@example.test','Demo-Changed-password2!');
  await expect(page.getByRole('heading',{name:'Create Ticket',exact:true})).toBeVisible();
  await page.goto(`/tickets/${id}`);
  await expect(page.getByText('The network cable has been replaced. Please test the workstation again.')).toBeVisible();
  await expect(page.getByRole('region',{name:'Internal Notes',exact:true})).toHaveCount(0);
  await page.getByLabel('Public Comment',{exact:true}).fill('I can connect again. Thank you for fixing the issue.');
  await page.getByRole('button',{name:'Post Public Comment'}).click();
  await expect(page.getByText('Public Comment posted.')).toBeVisible();
  page.once('dialog',d=>d.accept());
  await page.getByRole('button',{name:'Problem Appears Resolved',exact:true}).click();
  await expect(page.getByText(/Reported at/)).toBeVisible();
  await shot('13-requester-resolution.png','Requester: แจ้งว่าปัญหาดูเหมือนได้รับการแก้ไข','ผู้แจ้งตอบกลับผ่าน Public Comment และกด Problem Appears Resolved โดยไม่มีส่วน Internal Notes');
  await page.goto('/admin/users');
  await expect(page.getByRole('heading',{name:'Forbidden',exact:true})).toBeVisible();
  await shot('14-role-access-denied.png','จำกัดสิทธิ์ตามบทบาท','Requester ไม่สามารถเข้าหน้าจัดการผู้ใช้ของ Administrator ได้');
  await logout();
  await login('queue-browser@example.test');
  await expect(page.getByRole('heading',{name:'Ticket Queue',exact:true})).toBeVisible();
  await page.goto(`/staff/tickets/${id}`);
  await expect(page.getByText(/Requester reports the problem appears resolved/)).toBeVisible();
  page.once('dialog',d=>d.accept());
  await page.getByLabel('Status',{exact:true}).selectOption('RESOLVED');
  await expect(page.getByLabel('Status',{exact:true})).toHaveValue('RESOLVED');
  await shot('15-staff-resolved.png','IT Staff: ยืนยันแก้ไขสำเร็จ','เจ้าหน้าที่เห็นการยืนยันจากผู้แจ้งและเปลี่ยนสถานะ Ticket เป็น Resolved');
  await page.goto('/staff/tickets');
  await expect(page.getByRole('status')).toContainText('23 tickets');
  await page.setViewportSize({width:390,height:844});
  await shot('16-mobile-staff-queue.png','มือถือ: คิวงาน','คิวงานบนหน้าจอมือถือใช้รูปแบบการ์ดแทนตาราง');
  await page.locator('.staff-cards article').first().scrollIntoViewIfNeeded();
  await page.screenshot({path:directory+'17-mobile-ticket-cards.png',animations:'disabled'});
  shots.push({file:'17-mobile-ticket-cards.png',title:'มือถือ: การ์ด Ticket',caption:'ภาพส่วนผลลัพธ์คิวงานบนมือถือ ขนาด 390 × 844',url:page.url(),viewport:page.viewportSize()});
  await page.setViewportSize({width:1440,height:1000});
  await logout();
  await login('admin-browser@example.test');
  await expect(page.getByRole('heading',{name:'User Management',exact:true})).toBeVisible();
  await shot('18-admin-user-management.png','Administrator: จัดการผู้ใช้','แสดงรายชื่อผู้ใช้ บทบาท สถานะ และคำสั่งเพิ่มหรือแก้ไขผู้ใช้');
  await page.getByRole('button',{name:'Create user',exact:true}).click();
  const dialog=page.getByRole('dialog');
  await dialog.getByLabel('Name',{exact:true}).fill('Pim Support');
  await dialog.getByLabel('Email',{exact:true}).fill('pim.support@example.test');
  await dialog.getByLabel('Role',{exact:true}).selectOption('IT_STAFF');
  await dialog.getByLabel('Initial password',{exact:true}).fill('Demo-Initial-password3!');
  await shot('19-admin-create-user.png','Administrator: เพิ่มผู้ใช้','กำหนดชื่อ อีเมล บทบาท และรหัสผ่านเริ่มต้นสำหรับเจ้าหน้าที่ใหม่');
  await dialog.getByRole('button',{name:'Save user'}).click();
  await expect(page.getByRole('button',{name:'Edit Pim Support'})).toBeVisible();
  await shot('20-admin-user-created.png','Administrator: เพิ่มผู้ใช้สำเร็จ','บัญชี Pim Support ปรากฏในรายการหลังบันทึกผ่านระบบจริง');
  await page.getByRole('button',{name:'Edit Pim Support'}).click();
  await shot('21-admin-edit-user.png','Administrator: แก้ไขผู้ใช้','หน้าต่างแก้ไขข้อมูล บทบาท และสถานะ Active ของผู้ใช้');
  await page.getByRole('button',{name:'Set new initial password'}).click();
  await shot('22-admin-reset-password.png','Administrator: ตั้งรหัสเริ่มต้นใหม่','หน้าต่างสำหรับตั้งและยืนยันรหัสผ่านเริ่มต้นใหม่ของผู้ใช้');
  await page.goto('/admin/users');
  await expect(page.getByRole('heading',{name:'User Management',exact:true})).toBeVisible();
  await page.setViewportSize({width:834,height:1112});
  await shot('23-tablet-user-management.png','แท็บเล็ต: จัดการผู้ใช้','หน้าจัดการผู้ใช้บน viewport 834 × 1112');
  await page.setViewportSize({width:1440,height:1000});
  await logout();
  await shot('24-logout.png','ออกจากระบบ','หลัง Logout ระบบกลับสู่หน้า Sign in');
} finally {
  await writeFile(directory+'manifest.json',JSON.stringify({capturedAt:new Date().toISOString(),source:'Real local app with isolated demo database; no mocked API responses',shots},null,2));
  await browser.close();
}
