import { test, expect } from "@playwright/test";
import { mkdir } from "node:fs/promises";
import { accessible } from "./evidence-support.js";

test("administrator: live create/edit/reset, security, responsive reflow and keyboard dialogs", async ({ page }) => {
  if (!process.env.E2E_AUTH_PASSWORD) throw new Error("Run node scripts/run-auth-e2e.mjs --user-management");
  const initial = "Initial-Password123!", replacement = "Replacement-Password456!";
  await page.goto("/admin/users");
  await page.getByLabel("Email", { exact: false }).fill("admin-browser@example.test");
  await page.getByLabel("Password", { exact: false }).fill(process.env.E2E_AUTH_PASSWORD);
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page.getByRole("heading", { name: "User Management" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Edit Mali Administrator" })).toBeVisible();
  await mkdir("../artifacts/lab-03/screenshots/user-management", { recursive: true });
  for (const [name, width, height] of [["desktop", 1440, 900], ["tablet", 834, 1112], ["mobile", 390, 844], ["reflow-200-percent", 720, 450]] as const) {
    await page.setViewportSize({ width, height });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await accessible(page);
    await page.screenshot({ path: `../artifacts/lab-03/screenshots/user-management/${name}.png`, fullPage: true });
    await page.getByRole("button", { name: "Create user", exact: true }).click();
    const dialog = page.getByRole("dialog");
    await expect(dialog.getByLabel("Name", { exact: true })).toBeFocused();
    await expect(dialog.getByRole("button", { name: "Save user" })).toBeVisible();
    expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
    await accessible(page);
    await page.screenshot({ path: `../artifacts/lab-03/screenshots/user-management/${name}-create.png`, fullPage: true });
    await dialog.getByRole("button", { name: "Cancel", exact: true }).focus();
    await page.keyboard.press("Tab");
    expect(await page.evaluate(() => !!document.activeElement?.closest("dialog"))).toBe(true);
    await page.keyboard.press("Escape");
    await expect(page.getByRole("button", { name: "Create user", exact: true })).toBeFocused();
  }
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.getByRole("button", { name: "Create user", exact: true }).click();
  let dialog = page.getByRole("dialog");
  await dialog.getByLabel("Name", { exact: true }).fill("Niran Support");
  await dialog.getByLabel("Email", { exact: true }).fill("niran@example.test");
  await dialog.getByLabel("Role", { exact: true }).selectOption("IT_STAFF");
  await dialog.getByLabel("Initial password", { exact: true }).fill(initial);
  await dialog.getByRole("button", { name: "Save user" }).click();
  await expect(page.getByRole("status").filter({ hasText: "User saved" })).toBeVisible();
  await page.getByLabel("Search name or email").fill("NIRAN@");
  await page.getByRole("button", { name: "Search", exact: true }).click();
  await expect(page.getByRole("button", { name: "Edit Niran Support" })).toBeVisible();
  await page.getByRole("button", { name: "Edit Niran Support" }).click();
  dialog = page.getByRole("dialog");
  await dialog.getByLabel("Email", { exact: true }).fill("ADMIN-BROWSER@example.test");
  await dialog.getByRole("button", { name: "Save user" }).click();
  await expect(dialog.getByRole("alert")).toContainText("already in use");
  await dialog.getByLabel("Email", { exact: true }).fill("niran@example.test");
  await dialog.getByLabel("Name", { exact: true }).fill("Niran Updated");
  await dialog.getByLabel("Active", { exact: true }).uncheck();
  await dialog.getByRole("button", { name: "Save user" }).click();
  await expect(page.getByRole("table")).toContainText("Inactive");
  await page.getByRole("button", { name: "Edit Niran Updated" }).click();
  await page.getByRole("dialog").getByLabel("Active", { exact: true }).check();
  await page.getByRole("dialog").getByRole("button", { name: "Save user" }).click();
  await expect(page.getByRole("table")).toContainText("Active");
  await page.getByRole("button", { name: "Edit Niran Updated" }).click();
  await page.getByRole("button", { name: "Set new initial password" }).click();
  await page.getByLabel("Initial password", { exact: true }).fill(replacement);
  await page.getByLabel("Confirm initial password", { exact: true }).fill(replacement);
  await page.getByRole("button", { name: "Confirm new initial password" }).click();
  await expect(page.getByRole("status").filter({ hasText: "must change it at next login" })).toBeVisible();
  await page.getByRole("button", { name: "Clear filters" }).click();
  await page.getByRole("button", { name: "Edit Mali Administrator" }).click();
  await expect(page.getByLabel("Active", { exact: true })).toBeDisabled();
  await page.getByLabel("Role", { exact: true }).selectOption("REQUESTER");
  await page.getByRole("button", { name: "Save user" }).click();
  await expect(page.getByRole("alert")).toContainText("at least one active Administrator");
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  await page.getByRole("button", { name: "Logout", exact: true }).click();
  await page.getByLabel("Email", { exact: false }).fill("niran@example.test");
  await page.getByLabel("Password", { exact: false }).fill(replacement);
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page).toHaveURL(/change-password/);
  await page.getByRole("textbox", { name: "Current Password", exact: true }).fill(replacement);
  await page.getByRole("textbox", { name: "New Password", exact: true }).fill("Final-Password789!");
  await page.getByRole("textbox", { name: "Confirm New Password", exact: true }).fill("Final-Password789!");
  await page.getByRole("button", { name: "Save password", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Ticket Queue", exact: true })).toBeVisible();
  await page.goto("/admin/users");
  await expect(page.getByRole("heading", { name: "Forbidden" })).toBeVisible();
  expect((await page.request.get(`${process.env.E2E_API_URL}/api/admin/users`)).status()).toBe(403);
});
